GET http://localhost:8080/api/meals

###
POST http://localhost:8080/api/meals
content-type: application/json

{
	"Name": "Pasta"
}

###
PUT http://localhost:8080/api/meals/1
content-type: application/json

{
	"Name": "Pasta mit Sauce",
	"Link": "Betty Bossi",
	"Description": "Hmm... fein"
}

###
DELETE http://localhost:8080/api/meals/8

###
GET http://localhost:8080/api/mealdates

###
GET http://localhost:8080/api/mealdates/10

###
POST http://localhost:8080/api/mealdates
content-type: application/json

{
	"Date": "2030-06-20T01:01:01Z",
	"Type": "Lunch",
	"Meal": {
		"Name": "Hamburger"
	}
}